spring:
  application:
    name: shopapp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MYSQL8Dialect
  config:
    enable-config-properties-scanning: true
server:
  port: 8088
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30days = 30*24*60*60
  secretKey: cFmLSOGF4ZzbDeQWuekjEoOasYeDECiB/XbHqogCays=

