spring:
  application:
    name: shopapp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MYSQL8Dialect
  config:
    enable-config-properties-scanning: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
server:
  port: 8088
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30days = 30*24*60*60
  secretKey: cFmLSOGF4ZzbDeQWuekjEoOasYeDECiB/XbHqogCays=
vn-pay:
  secret-key: S8DSBROENXEJND84F9EUBRAPE0WM3YDZ
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8088/vnpay_return
  tmn-code: RKAQ2FOK
  version: 2.1.0
  command: pay


